version: "3"
services:
  bootstrap:
    image: quorumcontrol/tupelo:${TUPELO_VERSION:-master}
    command: ["bootstrap-node", "--config", "/configs/bootstrap/config.toml", "-L", "${TUPELO_LOG_LEVEL:-info}"]
    volumes:
      - ./localtupelo/configs:/configs      
    networks:
      default:
        ipv4_address: 172.16.238.10
    ports:
      - "34001:34001"
      
  node0:
    depends_on: 
      - bootstrap
    image: quorumcontrol/tupelo:${TUPELO_VERSION:-master}
    volumes:
      - ./localtupelo/configs:/configs      
    command: ["node", "--config", "/configs/node0/config.toml",
      "-L", "${TUPELO_LOG_LEVEL:-info}"]
    networks:
      default:
        ipv4_address: 172.16.238.11  
    ports:
      - "50000:50000"  

  node1:
    depends_on: 
      - bootstrap
    image: quorumcontrol/tupelo:${TUPELO_VERSION:-master}
    volumes:
      - ./localtupelo/configs:/configs      
    command: ["node", "--config", "/configs/node1/config.toml",
      "-L", "${TUPELO_LOG_LEVEL:-info}"]
  
  node2:
    depends_on: 
      - bootstrap
    image: quorumcontrol/tupelo:${TUPELO_VERSION:-master}
    volumes:
      - ./localtupelo/configs:/configs      
    command: ["node", "--config", "/configs/node2/config.toml",
      "-L", "${TUPELO_LOG_LEVEL:-info}"]

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24


# version: "3"
# services:
#   bootstrap:
#     image: quorumcontrol/tupelo:${TUPELO_VERSION:-master}
#     command: ["bootstrap-node", "--config", "/configs/bootstrap/config.toml", "-L", "${TUPELO_LOG_LEVEL:-error}"]
#     volumes:
#       - ./localtupelo/configs:/configs      
#     networks:
#       default:
#         ipv4_address: 172.16.238.10
#     ports:
#       - "34001:34001"
      
#   node0:
#     depends_on: 
#       - bootstrap
#     image: quorumcontrol/tupelo:${TUPELO_VERSION:-master}
#     volumes:
#       - ./localtupelo/configs:/configs      
#     command: ["node", "--config", "/configs/node0/config.toml",
#       "-L", "${TUPELO_LOG_LEVEL:-error}"]
#     ports:
#       - "50000:50000"
#     networks:
#       default:
#         ipv4_address: 172.16.238.11

#   node1:
#     depends_on: 
#       - bootstrap
#     image: quorumcontrol/tupelo:master
#     volumes:
#       - ./localtupelo/configs:/configs      
#     command: ["node", "--config", "/configs/node1/config.toml",
#       "-L", "${TUPELO_LOG_LEVEL:-error}"]
  
#   node2:
#     depends_on: 
#       - bootstrap
#     image: quorumcontrol/tupelo:${TUPELO_VERSION:-master}
#     volumes:
#       - ./localtupelo/configs:/configs      
#     command: ["node", "--config", "/configs/node2/config.toml",
#       "-L", "${TUPELO_LOG_LEVEL:-error}"]

# networks:
#   default:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.16.238.0/24
