Name = "integrationtest"
Shards = 32

CacheMessages = false
CacheBlocks = true
RebroadcastCommit = true
TrackPeers = false

NotaryGroupConfig = "./wasmdocker.toml"
WebsocketPort = 50000

[Storage]
Kind = "memory"
