version: "3"
services:
  buildwasm:
    build: .
    command: "go build -ldflags='-s -w' -o /out/tupelo.wasm"
    working_dir: /app/wasm
    volumes:
      - ./tupelo-go-sdk:/app:delegated
      - ./.tmp:/root/.cache:delegated
      - $GOPATH/pkg/mod:/go/pkg/mod:delegated
      - ./out:/out:delegated
    environment:
      GOPATH: /go
      GOOS: js 
      GOARCH: wasm