name: Run each example

on: [push]

jobs:
  ownerhsip-transfer:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm i -g ts-node
      - name: ownership transfer example
        run: |
          cd examples/ownership-transfer
          npm install
          ts-node run src
  set-get-data-example:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm i -g ts-node
      - name: set-and-get-data example
        run: |
          cd examples/set-and-get-data
          npm install
          ts-node run src
  token-exmaples:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm i -g ts-node  
      - name: set-and-get-data example
        run: |
          cd examples/tokens
          npm install
          ts-node run src
