name: Publish NPM package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: version check
        run: scripts/ci-release-ver-check.sh
      - run: cd wasmtupelo && docker-compose up -d
      - run: npm install
      - name: git setup
        run: scripts/ci-gitsetup.sh
      - name: build wasm and javascript
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: scripts/ci-build.sh
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
