name: Publish NPM package

on:
  release:
    types: [published]

jobs:
  publish:
    needs:
      - build-sdk
      - test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: version check
        run: scripts/ci-release-ver-check.sh
      - run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
