name: Build WASM and Test

on: [push]

jobs:
  build-sdk:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install deps
        run: npm install
      - name: Build SDK
        run: npm run build
  test:
    needs: build-sdk
    runs-on: ubuntu-18.04
    steps:
      - run: npm run test-suite
